apiVersion: v1
kind: LimitRange
metadata:
  name: ephemeral-storage-1gi
spec:
  limits:
    - type: Container
      max:
        ephemeral-storage: "100Mi"
      default:
        ephemeral-storage: "50Mi"
      defaultRequest:
        ephemeral-storage: "50Mi"
