apiVersion: v1
kind: LimitRange
metadata:
  name: ephemeral-storage-1gi
spec:
  limits:
    - type: Container
      max:
        ephemeral-storage: "1Gi"
      min:
        ephemeral-storage: "256Mi"
      default:
        ephemeral-storage: "256Mi"
      defaultRequest:
        ephemeral-storage: "128Mi"
