apiVersion: v1
kind: LimitRange
metadata:
  name: ephemeral-storage-limits
spec:
  limits:
    - type: Container
      defaultRequest:
        ephemeral-storage: "64Mi"
      default:
        ephemeral-storage: "256Mi"
      min:
        ephemeral-storage: "32Mi"
      max:
        ephemeral-storage: "2Gi"
