apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
    xyz: "hello"
  name: nginx
  namespace: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx:1.7.9
        name: nginx
