apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubernetes-deployment
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:adilosch/kubernetes-deployment.git
    targetRevision: HEAD
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: nginx
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
